# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.

metatag.metatag_tag.schema_educational_occupational_program_application_deadline:
  type: text
  label: 'applicationDeadline'
metatag.metatag_tag.schema_educational_occupational_program_application_start_date:
  type: text
  label: 'applicationStartDate'
metatag.metatag_tag.schema_educational_occupational_program_day_of_week:
  type: text
  label: 'dayOfWeek'
metatag.metatag_tag.schema_educational_occupational_program_description:
  type: text_long
  label: 'description'
metatag.metatag_tag.schema_educational_occupational_program_educational_credential_awarded:
  type: text
  label: 'educationalCredentialAwarded'
metatag.metatag_tag.schema_educational_occupational_program_educational_program_mode:
  type: text
  label: 'educationalProgramMode'
metatag.metatag_tag.schema_educational_occupational_program_end_date:
  type: text
  label: 'endDate'
metatag.metatag_tag.schema_educational_occupational_program_financial_aid_eligible:
  type: text
  label: 'financialAidEligible'
metatag.metatag_tag.schema_educational_occupational_program_identifier:
  type: text
  label: 'identifier'
metatag.metatag_tag.schema_educational_occupational_program_maximum_enrollment:
  type: text
  label: 'maximumEnrollment'
metatag.metatag_tag.schema_educational_occupational_program_name:
  type: text
  label: 'name'
metatag.metatag_tag.schema_educational_occupational_program_number_of_credits:
  type: text
  label: 'numberOfCredits'
metatag.metatag_tag.schema_educational_occupational_program_occupational_category:
  type: text
  label: 'occupationalCategory'
metatag.metatag_tag.schema_educational_occupational_program_occupational_credential_awarded:
  type: text
  label: 'occupationalCredentialAwarded'
metatag.metatag_tag.schema_educational_occupational_program_offers:
  type: text
  label: 'offers'
metatag.metatag_tag.schema_educational_occupational_program_program_prerequisites:
  type: text
  label: 'programPrerequisites'
metatag.metatag_tag.schema_educational_occupational_program_program_type:
  type: text
  label: 'programType'
metatag.metatag_tag.schema_educational_occupational_program_provider:
  type: text
  label: 'provider'
metatag.metatag_tag.schema_educational_occupational_program_salary_upon_completion:
  type: text
  label: 'salaryUponCompletion'
metatag.metatag_tag.schema_educational_occupational_program_start_date:
  type: text
  label: 'startDate'
metatag.metatag_tag.schema_educational_occupational_program_term_duration:
  type: text
  label: 'termDuration'
metatag.metatag_tag.schema_educational_occupational_program_terms_per_year:
  type: text
  label: 'termsPerYear'
metatag.metatag_tag.schema_educational_occupational_program_time_of_day:
  type: text
  label: 'timeOfDay'
metatag.metatag_tag.schema_educational_occupational_program_time_to_complete:
  type: text
  label: 'timeToComplete'
metatag.metatag_tag.schema_educational_occupational_program_training_salary:
  type: text
  label: 'trainingSalary'
metatag.metatag_tag.schema_educational_occupational_program_type:
 type: text
 label: 'type'
metatag.metatag_tag.schema_educational_occupational_program_typical_credits_per_term:
  type: text
  label: 'typicalCreditsPerTerm'
metatag.metatag_tag.schema_educational_occupational_program_url:
  type: text
  label: 'url'
